name: Add codesandbox link

on: pull_request
  

jobs:
  codesandbox-comment:
    name: Add codesandbox link comment
    runs-on: ubuntu-latest
    steps:
      
        with:
          message: |
            You can check this code at CodeSandbox with the link
            https://githubbox.com/${{ github.repository }}/tree/${{ github.head_ref }}